package com.example.easelife.data.tables;

import com.example.easelife.data.tables.meters.AllMetersData;

import java.sql.Date;

import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;


@Entity
public class TableHouse {

    @ColumnInfo
    @PrimaryKey(autoGenerate = true)
    public int houseId;

    @ColumnInfo(defaultValue = "NULL")
    public String houseName;

    @ColumnInfo()
    public Date date;

    @ColumnInfo(defaultValue = "0")
    public int noOfRooms;

    @ColumnInfo(defaultValue = "0")
    public int occupiedRooms;

    @ColumnInfo(defaultValue = "false")
    public boolean includeMeter;

    @ColumnInfo()
    public long meterid;


    @Embedded
    public Address address;

    @Ignore
    public boolean ismetersystemgenerated;

    @Ignore
    public boolean isRoomAutoGenerated;

    @Ignore
    public int houseIdForAutoRoom;

    @Ignore
    public boolean isDeleteHouseByid;
    @Ignore
    public AllMetersData allMetersData = new AllMetersData();

    @Ignore
    public TableHouse setDeleteHouseByid(boolean deleteHouseByid) {
        isDeleteHouseByid = deleteHouseByid;
        return this;
    }

    public AllMetersData getAllMetersData() {
        return this.allMetersData;
    }


    public int getHouseId() {
        return houseId;
    }

    public String getHouseName() {
        return houseName;
    }

    public Date getDate() {
        return date;
    }

    public int getNoOfRooms() {
        return noOfRooms;
    }

    public int getOccupiedRooms() {
        return occupiedRooms;
    }

    public long getMeterid() {
        return meterid;
    }

    public TableHouse setHouseId(int houseId) {
        this.houseId = houseId;
        return this;
    }

    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    public void setDate(Date date) {
        this.date = date;
        allMetersData.date = date;
    }

    public void setNoOfRooms(int noOfRooms) {
        this.noOfRooms = noOfRooms;
    }

    public int setNoOfRoomsFromString(String noOfRoomsFromString) {
        if (noOfRoomsFromString.length() != 0) {
            this.noOfRooms = Integer.parseInt(noOfRoomsFromString);
        }
        return this.noOfRooms;
    }

    public void setOccupiedRooms(int occupiedRooms) {
        this.occupiedRooms = occupiedRooms;
    }

    public void setMeterid(long meterid) {
        this.meterid = meterid;
        this.allMetersData.meterId = meterid;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public boolean isIncludeMeter() {
        return includeMeter;
    }

    public void setIncludeMeter(boolean includeMeter) {
        this.includeMeter = includeMeter;
    }

    @Override
    public String toString() {
        return "TableHouse{" +
                "houseId=" + houseId +
                ", houseName='" + houseName  +
                ", date='" + date  +
                ", noOfRooms=" + noOfRooms +
                ", emptyrooms=" + occupiedRooms +
                ", includeMeter=" + includeMeter +
                ", meterid=" + meterid +
                ", address=" + getAddress() +
                "}";
    }

    private String getAddress() {
        if (address != null) {
            return address.toString();
        }else return "slkdjflsjf";
    }
}
