package com.tentlers.mngapp.data.tables;

import com.tentlers.mngapp.data.tables.meters.AllMetersData;

import java.sql.Date;

import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;


@Entity
public class TableHouse {
    @ColumnInfo(defaultValue = "false")
    public boolean isMeterIncluded;

    @ColumnInfo
    @PrimaryKey(autoGenerate = true)
    public int houseId;
    @ColumnInfo(defaultValue = "NULL")
    private String houseName;

    @ColumnInfo()
    private Date date;

    @ColumnInfo(defaultValue = "0")
    private int noOfRooms;

    @ColumnInfo(defaultValue = "0")
    private int occupiedRooms;
    @ColumnInfo()
    private long meterid;
    @Embedded
    private Address address;
    @Ignore
    private boolean ismetersystemgenerated;
    @Ignore
    private boolean isRoomAutoGenerated;
    @Ignore
    private int houseIdForAutoRoom;
    @Ignore
    private boolean isDeleteHouseByid;
    @Ignore
    private AllMetersData allMetersData;

    public TableHouse() {
        allMetersData = new AllMetersData();
    }


    public TableHouse setDeleteHouseByid(boolean deleteHouseByid) {
        isDeleteHouseByid = deleteHouseByid;
        return this;
    }

    public AllMetersData getAllMetersData() {
        return this.allMetersData;
    }


    public int getHouseId() {
        return houseId;
    }

    public TableHouse setHouseId(int houseId) {
        this.houseId = houseId;
        return this;
    }

    public String getHouseName() {
        return houseName;
    }

    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
        getAllMetersData().setDate(date);
    }

    public int getNoOfRooms() {
        return noOfRooms;
    }

    public void setNoOfRooms(int noOfRooms) {
        this.noOfRooms = noOfRooms;
    }

    public int getOccupiedRooms() {
        return occupiedRooms;
    }

    public void setOccupiedRooms(int occupiedRooms) {
        this.occupiedRooms = occupiedRooms;
    }

    public long getMeterid() {
        return meterid;
    }

    public void setMeterid(long meterid) {
        this.meterid = meterid;
        this.getAllMetersData().setMeterId(meterid);
    }

    public int setNoOfRoomsFromString(String noOfRoomsFromString) {
        if (noOfRoomsFromString.length() != 0) {
            this.setNoOfRooms(Integer.parseInt(noOfRoomsFromString));
        }
        return this.getNoOfRooms();
    }

    public boolean getIsMeterIncluded() {
        return isMeterIncluded;
    }

    public void setIsMeterIncluded(boolean meterIncluded) {
        this.isMeterIncluded = meterIncluded;
    }


    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public boolean isIsmetersystemgenerated() {
        return ismetersystemgenerated;
    }

    public void setIsmetersystemgenerated(boolean ismetersystemgenerated) {
        this.ismetersystemgenerated = ismetersystemgenerated;
    }

    public boolean isRoomAutoGenerated() {
        return isRoomAutoGenerated;
    }

    public void setRoomAutoGenerated(boolean roomAutoGenerated) {
        isRoomAutoGenerated = roomAutoGenerated;
    }

    public int getHouseIdForAutoRoom() {
        return houseIdForAutoRoom;
    }

    public void setHouseIdForAutoRoom(int houseIdForAutoRoom) {
        this.houseIdForAutoRoom = houseIdForAutoRoom;
    }

    public boolean isDeleteHouseByid() {
        return isDeleteHouseByid;
    }

    public void setAllMetersData(AllMetersData allMetersData) {
        this.allMetersData = allMetersData;
    }
}
