package com.tentlers.mngapp.data.tables;

import com.tentlers.mngapp.data.tables.meters.AllMeters;
import com.tentlers.mngapp.data.tables.meters.AllMetersData;

import java.util.Date;
import java.util.Formatter;

import androidx.room.ColumnInfo;
import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;


@Entity
public class TableHouse {

    public static final String HOUSE_ID = "houseId";

    @ColumnInfo(defaultValue = "false")
    public boolean isMeterIncluded;

    @ColumnInfo
    @PrimaryKey(autoGenerate = true)
    public long houseId;
    @ColumnInfo(defaultValue = "NULL")
    private String houseName;

    @ColumnInfo()
    private java.util.Date date;

    @ColumnInfo(defaultValue = "0")
    private int noOfRooms;

    @ColumnInfo(defaultValue = "0")
    private int occupiedRooms;
    @ColumnInfo()
    private long meterid;
    @Embedded
    private Address address;
    @Ignore
    private boolean ismetersystemgenerated;
    @Ignore
    private boolean isRoomAutoGenerated;
    @Ignore
    private long houseIdForAutoRoom;
    @Ignore
    private boolean isDeleteHouseByid;

    @Ignore
    private AllMetersData allMetersData;

    @Ignore
    private AllMeters allMeters;
    @Ignore
    public long meterNo;

    public TableHouse() {
        allMetersData = new AllMetersData();
    }


    public TableHouse setDeleteHouseByid(boolean deleteHouseByid) {
        isDeleteHouseByid = deleteHouseByid;
        return this;
    }

    public AllMetersData getAllMetersData() {
        return this.allMetersData;
    }

    @Deprecated
    public void setAllMetersData(AllMetersData allMetersData) {
        this.allMetersData = allMetersData;
    }


    public long getHouseId() {
        return houseId;
    }

    public TableHouse setHouseId(long houseId) {
        this.houseId = houseId;
        return this;
    }

    public String getHouseName() {
        return houseName;
    }

    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
        getAllMetersData().setDate(date);/*for setting the entry date*/
        getAllMeters().setCreatedate(date);

    }

    public int getNoOfRooms() {
        return noOfRooms;
    }

    public void setNoOfRooms(int noOfRooms) {
        this.noOfRooms = noOfRooms;
    }

    public int getOccupiedRooms() {
        return occupiedRooms;
    }

    public void setOccupiedRooms(int occupiedRooms) {
        this.occupiedRooms = occupiedRooms;
    }

    public long getMeterid() {
        return meterid;
    }

    public void setMeterid(long meterid) {
        this.meterid = meterid;
        this.allMetersData.setMeterId(meterid);
    }

    public int setNoOfRoomsFromString(String noOfRoomsFromString) {
        if (noOfRoomsFromString.length() != 0) {
            this.setNoOfRooms(Integer.parseInt(noOfRoomsFromString));
        }
        return this.getNoOfRooms();
    }

    public boolean getIsMeterIncluded() {
        return isMeterIncluded;
    }

    public void setIsMeterIncluded(boolean meterIncluded) {
        this.isMeterIncluded = meterIncluded;
    }


    public Address getAddress() {
        return this.address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public boolean isIsmetersystemgenerated() {
        return ismetersystemgenerated;
    }

    public void setIsmetersystemgenerated(boolean ismetersystemgenerated) {
        this.ismetersystemgenerated = ismetersystemgenerated;
    }

    public boolean isRoomAutoGenerated() {
        return isRoomAutoGenerated;
    }

    public void setRoomAutoGenerated(boolean roomAutoGenerated) {
        isRoomAutoGenerated = roomAutoGenerated;
    }

    public long getHouseIdForAutoRoom() {
        return houseIdForAutoRoom;
    }

    public void setHouseIdForAutoRoom(long houseIdForAutoRoom) {
        this.houseIdForAutoRoom = houseIdForAutoRoom;
    }

    public boolean isDeleteHouseByid() {
        return isDeleteHouseByid;
    }

    @Ignore
    public static String getHouseDate(java.util.Date createDate) {
        Formatter formatter = new Formatter();
        return formatter.format("%td %th, %tY", createDate, createDate, createDate).toString();
    }

    public AllMeters getAllMeters() {
        if (allMeters == null) {
            this.allMeters = new AllMeters();
        }
        return allMeters;
    }

    public void setAllMeters(AllMeters allMeters) {
        this.allMeters = allMeters;
    }
}
